# Generated by Django 4.0 on 2022-03-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='description_en',
            field=models.CharField(max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
    ]
