# Generated by Django 4.0 on 2022-03-16 14:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videomodel_description_en_videomodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=300, null=True, verbose_name='description'),
        ),
    ]
