# Generated by Django 4.1.1 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videomodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_en',
            field=models.TextField(max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description_uz',
            field=models.TextField(max_length=300, null=True, verbose_name='description'),
        ),
    ]
