# Generated by Django 4.0 on 2022-07-05 13:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('short_descriptions', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='short_description')),
                ('image', models.FileField(upload_to='gallery_image', verbose_name='image')),
                ('long_descriptions', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='long_description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
    ]
