# Generated by Django 4.0 on 2022-07-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='video',
            field=models.FileField(null=True, upload_to='gallery_video', verbose_name='video'),
        ),
    ]
