# Generated by Django 4.0 on 2022-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='name',
            field=models.CharField(max_length=222, null=True, verbose_name='asd'),
        ),
    ]
