# Generated by Django 4.0 on 2022-07-06 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerymodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='video',
            field=models.FileField(null=True, upload_to='gallery_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='video'),
        ),
    ]
