# Generated by Django 4.0 on 2022-07-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerymodel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='video',
        ),
    ]
