# Generated by Django 4.0 on 2022-07-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_galleyimagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleyimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images', verbose_name='image'),
        ),
    ]
