# Generated by Django 4.0 on 2022-07-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_galleyimagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='image',
        ),
    ]
