# Generated by Django 4.0 on 2022-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_gallerymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
