# Generated by Django 4.0 on 2022-07-06 12:24

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_gallerymodel_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='last_date',
            field=models.DateField(null=True, verbose_name='last_date'),
        ),
    ]
