# Generated by Django 4.0 on 2022-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_galleyimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleyimagemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery_images', verbose_name='image'),
        ),
    ]
