# Generated by Django 4.1.1 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_galleyimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions_en',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions_ru',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions_uz',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions_en',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions_ru',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions_uz',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
    ]
