# Generated by Django 4.0 on 2022-07-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_gallerymodel_url_alter_gallerymodel_last_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerymodel',
            old_name='url',
            new_name='video',
        ),
    ]
