# Generated by Django 4.0 on 2022-07-06 12:33

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_rename_url_gallerymodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True, verbose_name='video'),
        ),
    ]
