# Generated by Django 4.0 on 2022-07-07 07:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_gallerymodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='long_descriptions_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='long_descriptions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='long_descriptions_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='short_descriptions_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='short_descriptions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='short_descriptions_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
    ]
