# Generated by Django 4.0 on 2022-07-07 10:04

import ckeditor_uploader.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_gallerymodel_long_descriptions_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='last_date',
            field=models.DateField(blank=True, null=True, verbose_name='last_date'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='long_descriptions_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='short_descriptions_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='video'),
        ),
    ]
