# Generated by Django 4.0 on 2021-12-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
