# Generated by Django 4.0 on 2022-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogmodel_smart_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='smart_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='smart_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='smart_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='smart_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='smart_text'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='smart_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='smart_text'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='smart_text_uz',
            field=models.TextField(blank=True, null=True, verbose_name='smart_text'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=40, null=True, verbose_name='title'),
        ),
    ]
