# Generated by Django 4.0 on 2022-03-16 14:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_description_en_blogmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_text'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_text'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_text'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_text_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='smart_text'),
        ),
    ]
