# Generated by Django 4.0 on 2022-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogmodel_smart_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
