# Generated by Django 4.1.1 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description',
            field=models.TextField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='smart_description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='smart_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='smart_description'),
        ),
    ]
