# Generated by Django 4.0.1 on 2022-02-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiznesImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='biznes_single', verbose_name='biznes_image')),
                ('work_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biznes_image', to='biznes.biznesmodel', verbose_name='biznes_image')),
            ],
            options={
                'verbose_name': 'biznes_image',
                'verbose_name_plural': 'biznes_image',
            },
        ),
    ]
