# Generated by Django 4.0 on 2022-03-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0002_biznesimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='biznesmodel',
            name='long_descriptions_en',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
        migrations.AddField(
            model_name='biznesmodel',
            name='long_descriptions_ru',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
        migrations.AddField(
            model_name='biznesmodel',
            name='long_descriptions_uz',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
        migrations.AddField(
            model_name='biznesmodel',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='biznesmodel',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='biznesmodel',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
    ]
