# Generated by Django 4.0 on 2022-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0007_alter_biznesimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biznesimagemodel',
            name='image',
            field=models.FileField(null=True, upload_to='biznes_single', verbose_name='biznes_image'),
        ),
    ]
