# Generated by Django 4.0 on 2022-04-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0009_alter_biznesimagemodel_biznes_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biznesimagemodel',
            name='biznes_image',
        ),
        migrations.RemoveField(
            model_name='biznesimagemodel',
            name='biznes_num',
        ),
        migrations.RemoveField(
            model_name='biznesimagemodel',
            name='biznes_spec',
        ),
        migrations.RemoveField(
            model_name='biznesimagemodel',
            name='image',
        ),
    ]
