# Generated by Django 4.0 on 2022-04-15 13:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0011_biznesimagemodel_biznes_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biznesmodel',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='title_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='title_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=250, null=True, verbose_name='title'),
        ),
    ]
