# Generated by Django 4.0 on 2022-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0012_alter_biznesmodel_title_alter_biznesmodel_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biznesmodel',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='title'),
        ),
    ]
