# Generated by Django 4.0 on 2022-09-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0013_alter_biznesmodel_title_alter_biznesmodel_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biznesimagemodel',
            name='biznes_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biznes_image', to='biznes.biznesmodel', verbose_name='biznes_image'),
        ),
        migrations.AlterField(
            model_name='biznesimagemodel',
            name='biznes_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='biznes_num'),
        ),
        migrations.AlterField(
            model_name='biznesimagemodel',
            name='biznes_spec',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='biznes_spec'),
        ),
        migrations.AlterField(
            model_name='biznesimagemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='biznes_single', verbose_name='biznes_image'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions',
            field=models.TextField(verbose_name='long_descriptions'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions_en',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions_ru',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions_uz',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
    ]
