# Generated by Django 4.0 on 2022-09-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0015_alter_biznesmodel_long_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biznesmodel',
            name='biznes_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
