# Generated by Django 4.0 on 2022-09-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0016_biznesmodel_biznes_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biznesmodel',
            old_name='biznes_views',
            new_name='views',
        ),
    ]
