# Generated by Django 4.1.1 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biznes', '0018_alter_biznesmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions',
            field=models.TextField(verbose_name='long_descriptions'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions_en',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions_ru',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
        migrations.AlterField(
            model_name='biznesmodel',
            name='long_descriptions_uz',
            field=models.TextField(null=True, verbose_name='long_descriptions'),
        ),
    ]
