# Generated by Django 4.0 on 2022-02-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('image', models.FileField(upload_to='line_image', verbose_name='image')),
                ('pdf', models.FileField(upload_to='line_pdf', verbose_name='line_pdf')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'line',
                'verbose_name_plural': 'lines',
            },
        ),
    ]
