# Generated by Django 4.0 on 2022-02-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSpecificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_specification', models.CharField(max_length=90, verbose_name='line_specification')),
                ('line_number', models.CharField(max_length=90, verbose_name='line_number')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lines.linemodel', verbose_name='title')),
            ],
            options={
                'verbose_name': 'line specification',
                'verbose_name_plural': 'line specifications',
            },
        ),
    ]
