# Generated by Django 4.0 on 2022-02-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_linespecificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linespecificationmodel',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='lines.linemodel', verbose_name='title'),
        ),
    ]
