# Generated by Django 4.0.1 on 2022-02-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_alter_linespecificationmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linespecificationmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='linespecificationmodel',
            name='line_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_image', to='lines.linemodel', verbose_name='line_image'),
        ),
    ]
