# Generated by Django 4.0.1 on 2022-02-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0004_remove_linespecificationmodel_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linespecificationmodel',
            name='line_number',
        ),
        migrations.RemoveField(
            model_name='linespecificationmodel',
            name='line_specification',
        ),
        migrations.AddField(
            model_name='linespecificationmodel',
            name='image',
            field=models.FileField(null=True, upload_to='line_image', verbose_name='image'),
        ),
    ]
