# Generated by Django 4.0 on 2022-03-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0006_linemodel_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'line',
                'verbose_name_plural': 'lines',
            },
        ),
        migrations.AddField(
            model_name='linemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lines.linecategorymodel', verbose_name='category'),
        ),
    ]
