# Generated by Django 4.0 on 2022-03-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0007_linecategorymodel_linemodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linecategorymodel',
            options={'verbose_name': 'line category', 'verbose_name_plural': 'line categories'},
        ),
    ]
