# Generated by Django 4.0 on 2022-03-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0008_alter_linecategorymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lines.linecategorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lines.linecategorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lines.linecategorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='long_description_en',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='long_description_ru',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='long_description_uz',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='linemodel',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
