# Generated by Django 4.0 on 2022-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0009_linemodel_category_en_linemodel_category_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linecategorymodel',
            name='category_en',
            field=models.CharField(max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='linecategorymodel',
            name='category_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='linecategorymodel',
            name='category_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='category'),
        ),
    ]
