# Generated by Django 4.0 on 2022-03-16 14:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0015_alter_linemodel_category_alter_linemodel_category_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='line_pdf', verbose_name='line_pdf'),
        ),
    ]
