# Generated by Django 4.0 on 2022-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0016_alter_linemodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='text')),
                ('text_uz', models.TextField(max_length=200, null=True, verbose_name='text')),
                ('text_ru', models.TextField(max_length=200, null=True, verbose_name='text')),
                ('text_en', models.TextField(max_length=200, null=True, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'line text',
                'verbose_name_plural': 'line texts',
            },
        ),
    ]
