# Generated by Django 4.0 on 2022-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0017_linetextmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category',
            field=models.TextField(max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category_en',
            field=models.TextField(max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category_ru',
            field=models.TextField(max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category_uz',
            field=models.TextField(max_length=100, null=True, verbose_name='category'),
        ),
    ]
