# Generated by Django 4.0 on 2022-04-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0019_alter_linecategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linespecificationmodel',
            name='line_num',
            field=models.CharField(max_length=99, null=True, verbose_name='line_spec'),
        ),
        migrations.AddField(
            model_name='linespecificationmodel',
            name='line_spec',
            field=models.CharField(max_length=99, null=True, verbose_name='line_spec'),
        ),
    ]
