# Generated by Django 4.0 on 2022-05-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0021_alter_linespecificationmodel_line_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linespecificationmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='line_image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='linespecificationmodel',
            name='line_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_image', to='lines.linemodel', verbose_name='line_image'),
        ),
    ]
