# Generated by Django 4.0 on 2022-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0022_alter_linespecificationmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemodel',
            name='banner_image',
            field=models.FileField(null=True, upload_to='line_image', verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='image',
            field=models.FileField(null=True, upload_to='line_img', verbose_name='image'),
        ),
    ]
