# Generated by Django 4.0 on 2022-05-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0023_linemodel_banner_image_alter_linemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linemodel',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='linemodel',
            name='banner',
            field=models.FileField(null=True, upload_to='line_image', verbose_name='banner'),
        ),
    ]
