# Generated by Django 4.0 on 2022-05-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0024_remove_linemodel_banner_image_linemodel_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linespecificationmodel',
            name='line_num',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='line_num'),
        ),
        migrations.AlterField(
            model_name='linespecificationmodel',
            name='line_spec',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='line_spec'),
        ),
    ]
