# Generated by Django 4.0 on 2022-09-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0026_linemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
