# Generated by Django 4.0 on 2022-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0027_alter_linemodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemodel',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
