<<<<<<< HEAD
# Generated by Django 4.0 on 2023-01-05 09:11
=======
# Generated by Django 4.0 on 2022-11-21 11:55
>>>>>>> 660589000a9e84aaa168c345d8ffdb155ea6c7c7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0029_remove_linemodel_category_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linemodel',
            options={'ordering': ['-pk'], 'verbose_name': 'line', 'verbose_name_plural': 'lines'},
        ),
    ]
