# Generated by Django 4.1.1 on 2023-01-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0030_alter_linemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category',
            field=models.TextField(max_length=300, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category_en',
            field=models.TextField(max_length=300, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='linecategorymodel',
            name='category_uz',
            field=models.TextField(max_length=300, null=True, verbose_name='category'),
        ),
    ]
