# Generated by Django 4.1.1 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0031_alter_linecategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='long_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='long_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='linemodel',
            name='long_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
    ]
