# Generated by Django 4.0 on 2021-12-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='title')),
                ('sku', models.CharField(max_length=90, verbose_name='sku')),
                ('image', models.ImageField(upload_to='banner', verbose_name='image')),
                ('price', models.IntegerField(verbose_name='price')),
                ('price_dollar', models.IntegerField(null=True, verbose_name='price_dollar')),
                ('error', models.CharField(max_length=30, null=True)),
                ('discount_percent', models.FloatField(default=0)),
                ('short_description', models.TextField(null=True, verbose_name='short_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'banner_info',
                'verbose_name_plural': 'banner_info',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=99, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SingleBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(null=True, upload_to='banner_image', verbose_name='banner_image')),
                ('error', models.CharField(max_length=30, null=True)),
                ('banner_description', models.TextField(null=True, verbose_name='banner_description')),
                ('bonus', models.CharField(max_length=120)),
                ('first_specifications', models.CharField(blank=True, max_length=99, verbose_name='first_specifications')),
                ('second_specifications', models.CharField(blank=True, max_length=99, verbose_name='second_specifications')),
                ('third_specifications', models.CharField(blank=True, max_length=99, verbose_name='third_specifications')),
                ('four_specifications', models.CharField(blank=True, max_length=99, verbose_name='four_specifications')),
                ('five_specifications', models.CharField(blank=True, max_length=99, verbose_name='five_specifications')),
                ('six_specifications', models.CharField(blank=True, max_length=99, verbose_name='six_specifications')),
                ('seven_specifications', models.CharField(blank=True, max_length=99, verbose_name='seven_specifications')),
                ('eight_specifications', models.CharField(blank=True, max_length=99, verbose_name='eight_specifications')),
                ('nine_specifications', models.CharField(blank=True, max_length=99, verbose_name='nine_specifications')),
                ('ten_specifications', models.CharField(blank=True, max_length=99, verbose_name='ten_specifications')),
                ('eleven_specifications', models.CharField(blank=True, max_length=99, verbose_name='eleven_specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('banner_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banner_price', to='home.bannerinfomodel')),
                ('banner_price_dollar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banner_price_dollar', to='home.bannerinfomodel')),
                ('banner_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banner_sku', to='home.bannerinfomodel')),
                ('banner_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banner', to='home.bannerinfomodel')),
            ],
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
    ]
