# Generated by Django 4.0 on 2021-12-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=50, verbose_name='error')),
            ],
            options={
                'verbose_name': 'error',
                'verbose_name_plural': 'errors',
            },
        ),
        migrations.AlterModelOptions(
            name='singlebannermodel',
            options={'verbose_name': 'single_banner', 'verbose_name_plural': 'single_banners'},
        ),
    ]
