# Generated by Django 4.0 on 2021-12-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_bannerinfomodel_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_dollar',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='price'),
        ),
    ]
