# Generated by Django 4.0 on 2021-12-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bannerinfomodel_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='discount'),
        ),
    ]
