# Generated by Django 4.0 on 2021-12-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_bannerinfomodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.CharField(max_length=50, null=True, verbose_name='inbox'),
        ),
    ]
