# Generated by Django 4.0 on 2021-12-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bannerinfomodel_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.CharField(max_length=50, null=True, verbose_name='delivery'),
        ),
    ]
