# Generated by Django 4.0 on 2021-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bannerinfomodel_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='inbox'),
        ),
    ]
