# Generated by Django 4.0 on 2021-12-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_secondsubcategorymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondsubcategorymodel',
            options={'verbose_name': 'second_subcategory', 'verbose_name_plural': 'second_subcategories'},
        ),
    ]
