# Generated by Django 4.0 on 2021-12-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_singlebannermodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.bannerinfomodel', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
        migrations.DeleteModel(
            name='ErrorModel',
        ),
        migrations.DeleteModel(
            name='SingleBannerModel',
        ),
    ]
