# Generated by Django 4.0 on 2022-02-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_bannerimagemodel_delete_errormodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='error',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='inbox',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='price_dollar',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='short_description',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf', verbose_name='pdf'),
        ),
    ]
