# Generated by Django 4.0 on 2022-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_bannerinfomodel_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='city',
            field=models.CharField(max_length=99, null=True, verbose_name='city'),
        ),
    ]
