# Generated by Django 4.0.2 on 2022-02-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_bannerinfomodel_options_bannerinfomodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='error',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='inbox'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_dollar',
            field=models.IntegerField(null=True, verbose_name='price_dollar'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='short_description',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
