# Generated by Django 4.0 on 2022-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_bannerinfomodel_delivery_bannerinfomodel_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='price_dollar',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='dollar',
            field=models.IntegerField(null=True, verbose_name='dollar'),
        ),
    ]
