# Generated by Django 4.0 on 2022-02-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_bannerinfomodel_price_dollar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='error',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_number',
            field=models.CharField(max_length=99, null=True, verbose_name='product_number'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='city',
            field=models.CharField(max_length=99, null=True, verbose_name='city'),
        ),
    ]
