# Generated by Django 4.0 on 2022-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_categorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.FileField(null=True, upload_to='category_image', verbose_name='category_image'),
        ),
    ]
