# Generated by Django 4.0 on 2022-02-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_specificationmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='product_custom',
        ),
        migrations.RemoveField(
            model_name='specificationmodel',
            name='product_number',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_number',
            field=models.CharField(max_length=99, null=True, verbose_name='product_number'),
        ),
        migrations.AlterField(
            model_name='specificationmodel',
            name='product_customs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.bannerinfomodel', verbose_name='product_custom'),
        ),
    ]
