# Generated by Django 4.0 on 2022-02-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_bannerinfomodel_product_custom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.DeleteModel(
            name='SpecificationModel',
        ),
    ]
