# Generated by Django 4.0 on 2022-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_bannerinfomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='product_customs',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs6'),
        ),
    ]
