# Generated by Django 4.0 on 2022-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_bannerinfomodel_product_customs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs10',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs10'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs11',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs11'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs12',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs12'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs2',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs2'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs3',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs3'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs4',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs4'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs5',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs5'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs6',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs6'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs7',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs7'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs8',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs8'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='product_customs9',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs9'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='product_customs',
            field=models.CharField(max_length=99, null=True, verbose_name='product_customs'),
        ),
    ]
