# Generated by Django 4.0 on 2022-02-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_productspecificationsmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecificationsmodel',
            old_name='product_custom',
            new_name='product_customer',
        ),
        migrations.AlterField(
            model_name='productspecificationsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='home.bannerinfomodel', verbose_name='products'),
        ),
    ]
