# Generated by Django 4.0 on 2022-02-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_product_custom_productspecificationsmodel_product_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='product_image',
            field=models.FileField(null=True, upload_to='pdf_image', verbose_name='product_image'),
        ),
    ]
