# Generated by Django 4.0 on 2022-02-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_productspecificationsmodel_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
    ]
