# Generated by Django 4.0.1 on 2022-02-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_subcategorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='image',
            field=models.FileField(null=True, upload_to='sub_image', verbose_name='sub_image'),
        ),
    ]
