# Generated by Django 4.0 on 2022-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_subcategorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productspecificationsmodel',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='pdf_image', verbose_name='product_image'),
        ),
    ]
