# Generated by Django 4.0 on 2022-02-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_bannerimagemodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='long_description',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
    ]
