# Generated by Django 4.0 on 2022-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_bannerinfomodel_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
