# Generated by Django 4.0 on 2022-02-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_bannerinfomodel_id_alter_bannerinfomodel_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='sku',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
