# Generated by Django 4.0 on 2022-02-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_bannerinfomodel_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'managed': True, 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
