# Generated by Django 4.0 on 2022-02-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_bannerinfomodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerinfomodel',
            old_name='sku',
            new_name='id',
        ),
    ]
