# Generated by Django 4.0 on 2022-02-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_sku_bannerinfomodel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='sku',
            field=models.CharField(max_length=90, null=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
