# Generated by Django 4.0 on 2022-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_bannerinfomodel_options_bannerinfomodel_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='sku',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
