# Generated by Django 4.0 on 2022-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_bannerinfomodel_id_alter_bannerinfomodel_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='created_at_uz',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
    ]
