# Generated by Django 4.0 on 2022-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_categorymodel_created_at_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='created_at_ru',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='created_at_uz',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_en',
            field=models.CharField(max_length=99, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_ru',
            field=models.CharField(max_length=99, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_uz',
            field=models.CharField(max_length=99, null=True, verbose_name='category'),
        ),
    ]
