# Generated by Django 4.0 on 2022-02-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_categorymodel_created_at_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='city_en',
            field=models.CharField(max_length=99, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='city_ru',
            field=models.CharField(max_length=99, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='city_uz',
            field=models.CharField(max_length=99, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='secondsubcategory_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.secondsubcategorymodel', verbose_name='second_subcategory'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='secondsubcategory_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.secondsubcategorymodel', verbose_name='second_subcategory'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='secondsubcategory_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.secondsubcategorymodel', verbose_name='second_subcategory'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='subcategory_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='subcategory_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='subcategory_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='title_en',
            field=models.CharField(max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='title_ru',
            field=models.CharField(max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='title_uz',
            field=models.CharField(max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='secondsubcategory_en',
            field=models.CharField(max_length=90, null=True, verbose_name='second_subcategory'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='secondsubcategory_ru',
            field=models.CharField(max_length=90, null=True, verbose_name='second_subcategory'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='secondsubcategory_uz',
            field=models.CharField(max_length=90, null=True, verbose_name='second_subcategory'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='subcategory_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='subcategory_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='secondsubcategorymodel',
            name='subcategory_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='subcategory_en',
            field=models.CharField(max_length=90, null=True, verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='subcategory_ru',
            field=models.CharField(max_length=90, null=True, verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='subcategory_uz',
            field=models.CharField(max_length=90, null=True, verbose_name='subcategory'),
        ),
    ]
