# Generated by Django 4.0 on 2022-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_bannerinfomodel_category_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, verbose_name='delivery'),
        ),
    ]
