# Generated by Django 4.0 on 2022-02-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_bannerinfomodel_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='price'),
        ),
    ]
