# Generated by Django 4.0 on 2022-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_bannerinfomodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='price'),
        ),
    ]
