# Generated by Django 4.0 on 2022-02-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_rename_category_english_bannerinfomodel_category_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='price'),
        ),
    ]
