# Generated by Django 4.0 on 2022-02-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_bannerinfomodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.CharField(blank=True, max_length=50, verbose_name='inbox'),
        ),
    ]
