# Generated by Django 4.0 on 2022-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_bannerinfomodel_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='sku',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title',
            field=models.CharField(db_index=True, max_length=99, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title_en',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='title'),
        ),
    ]
