# Generated by Django 4.0 on 2022-03-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_bannerinfomodel_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('descriptions', models.TextField(verbose_name='descriptions')),
                ('descriptions_en', models.TextField(null=True, verbose_name='descriptions')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='descriptions')),
                ('descriptions_uz', models.TextField(null=True, verbose_name='descriptions')),
                ('image', models.FileField(upload_to='Banner_home1', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'carousel',
                'verbose_name_plural': 'carousels',
            },
        ),
    ]
