# Generated by Django 4.0 on 2022-03-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_carouselmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='secondsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.secondsubcategorymodel', verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='secondsubcategory_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.secondsubcategorymodel', verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='secondsubcategory_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.secondsubcategorymodel', verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='secondsubcategory_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.secondsubcategorymodel', verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
    ]
