# Generated by Django 4.0 on 2022-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_bannerinfomodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='image',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='image'),
        ),
    ]
