# Generated by Django 4.0 on 2022-03-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_secondsubcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categorymodel', verbose_name='category'),
        ),
    ]
