# Generated by Django 4.0 on 2022-03-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_secondsubcategorymodel_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='subcategory_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='subcategory_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='subcategory_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
    ]
