# Generated by Django 4.0 on 2022-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.TextField(max_length=99, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_en',
            field=models.TextField(max_length=99, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_ru',
            field=models.TextField(max_length=99, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_uz',
            field=models.TextField(max_length=99, null=True, verbose_name='category'),
        ),
    ]
