# Generated by Django 4.0 on 2022-04-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_bannerinfomodel_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='sku',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
