# Generated by Django 4.0 on 2022-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='secondsubcategory',
            field=models.CharField(max_length=300, verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='secondsubcategory_en',
            field=models.CharField(max_length=300, null=True, verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='secondsubcategory_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='secondsubcategorymodel',
            name='secondsubcategory_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='second_subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory',
            field=models.CharField(max_length=300, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory_en',
            field=models.CharField(max_length=300, null=True, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='subcategory'),
        ),
    ]
