# Generated by Django 4.0 on 2022-05-23 12:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_secondsubcategorymodel_secondsubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='short_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='short_description'),
        ),
    ]
