# Generated by Django 4.0 on 2022-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_bannerinfomodel_long_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='delivery_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='delivery_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='delivery_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='inbox_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='inbox'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='inbox_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='inbox'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='inbox_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='inbox'),
        ),
    ]
