# Generated by Django 4.0 on 2022-06-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_bannerinfomodel_delivery_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'ordering': ['title'], 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
