# Generated by Django 4.0 on 2022-06-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_alter_bannerinfomodel_options'),
        ('home', '0077_remove_bannerinfomodel_secondsubcategory_and_more'),
    ]

    operations = [
    ]
