# Generated by Django 4.0 on 2022-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_merge_20220607_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerBackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='banner_back', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Banner_back',
                'verbose_name_plural': 'Banner_backs',
            },
        ),
    ]
