# Generated by Django 4.0 on 2022-06-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_bannerbackmodel_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=99, null=True, verbose_name='country')),
                ('image', models.FileField(upload_to='banner_country', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Banner_country',
                'verbose_name_plural': 'Banner_country',
            },
        ),
        migrations.AlterField(
            model_name='bannerbackmodel',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=99, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bannerbackmodel', verbose_name='background'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bannercountrymodel', verbose_name='country'),
        ),
    ]
