# Generated by Django 4.0 on 2022-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_bannercountrymodel_alter_bannerbackmodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='image',
            field=models.FileField(null=True, upload_to='banner', verbose_name='image'),
        ),
    ]
