# Generated by Django 4.0 on 2022-07-11 07:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_carouselmodel_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_index=True, max_length=400, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_index=True, max_length=400, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_index=True, max_length=400, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_index=True, max_length=400, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=300, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory_ru',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory_uz',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='subcategory'),
        ),
        migrations.AlterIndexTogether(
            name='bannerinfomodel',
            index_together={('title', 'category', 'subcategory', 'price', 'dollar')},
        ),
    ]
