# Generated by Django 4.0 on 2022-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='city',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='city_en',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='city_ru',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='city_uz',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='descriptions',
            field=models.TextField(db_index=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='descriptions_en',
            field=models.TextField(db_index=True, null=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='descriptions_ru',
            field=models.TextField(db_index=True, null=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='descriptions_uz',
            field=models.TextField(db_index=True, null=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=60, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='title_en',
            field=models.CharField(db_index=True, max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=60, null=True, verbose_name='title'),
        ),
    ]
