# Generated by Django 4.0 on 2022-07-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_categorymodel_language_code_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.categorymodel', verbose_name='category'),
        ),
    ]
