# Generated by Django 4.0 on 2022-07-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_alter_subcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subcategorymodel', verbose_name='subcategory'),
        ),
    ]
