# Generated by Django 4.0 on 2022-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_subcategorymodel_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='language_code_en',
            field=models.CharField(blank=True, choices=[('RU', 'ru'), ('EN', 'en'), ('UZ', 'uz')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='language_code_ru',
            field=models.CharField(blank=True, choices=[('RU', 'ru'), ('EN', 'en'), ('UZ', 'uz')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='language_code_uz',
            field=models.CharField(blank=True, choices=[('RU', 'ru'), ('EN', 'en'), ('UZ', 'uz')], max_length=2, null=True),
        ),
    ]
