# Generated by Django 4.0 on 2022-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_subcategorymodel_language_code_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='language_code',
            field=models.CharField(blank=True, choices=[('RU', 'ru'), ('EN', 'en'), ('UZ', 'uz')], max_length=2, null=True),
        ),
    ]
