# Generated by Django 4.0 on 2022-07-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_productspecificationsmodel_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificationsmodel',
            name='language_code',
        ),
    ]
