# Generated by Django 4.0 on 2022-07-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_alter_bannerinfomodel_index_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'ordering': ['title', 'pk'], 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
