# Generated by Django 4.0 on 2022-07-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_bannerinfomodel_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerinfomodel',
            old_name='url',
            new_name='video',
        ),
    ]
