# Generated by Django 4.0 on 2022-07-20 07:22

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_rename_url_bannerinfomodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
