# Generated by Django 4.0 on 2022-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_alter_bannerinfomodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
