# Generated by Django 4.0 on 2022-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_bannerinfomodel_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='background_color',
            field=models.CharField(blank=True, choices=[('yellow', 'yellow'), ('blue', 'blue'), ('red', 'red')], max_length=50, null=True),
        ),
    ]
