# Generated by Django 4.0 on 2022-07-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_alter_bannerinfomodel_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='background_color',
        ),
    ]
