# Generated by Django 4.0 on 2022-07-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_alter_categorymodel_options_categorymodel_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='CIP',
            field=models.BooleanField(default=False, verbose_name='CIP'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='DAF',
            field=models.BooleanField(default=False, verbose_name='DAF'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='EXW',
            field=models.BooleanField(default=False, verbose_name='EXW'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='FCA',
            field=models.BooleanField(default=False, verbose_name='FCA'),
        ),
    ]
