# Generated by Django 4.0 on 2022-07-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_alter_bannerinfomodel_cip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title',
            field=models.CharField(db_index=True, max_length=99, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title_en',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=99, null=True, verbose_name='title'),
        ),
    ]
