# Generated by Django 4.0 on 2022-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_alter_bannerinfomodel_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'ordering': ['my_order'], 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
