# Generated by Django 4.0 on 2022-07-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_alter_subcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'ordering': ['my_order', 'pk'], 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
