# Generated by Django 4.0 on 2022-07-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_alter_bannerinfomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'ordering': ['my_order'], 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
