# Generated by Django 4.0 on 2022-07-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_alter_bannerinfomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerinfomodel',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='my_product',
        ),
    ]
