# Generated by Django 4.0 on 2022-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_alter_bannerinfomodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='product_customer_en',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='product_customer'),
        ),
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='product_customer_ru',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='product_customer'),
        ),
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='product_customer_uz',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='product_customer'),
        ),
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='product_number_en',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='product_numbers'),
        ),
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='product_number_ru',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='product_numbers'),
        ),
        migrations.AddField(
            model_name='productspecificationsmodel',
            name='product_number_uz',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='product_numbers'),
        ),
    ]
