# Generated by Django 4.0 on 2022-08-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_alter_bannerinfomodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.subcategorymodel', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='subcategory_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.subcategorymodel', verbose_name='subcategory'),
        ),
    ]
