# Generated by Django 4.0 on 2022-09-24 12:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
    ]
