# Generated by Django 4.0 on 2022-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_alter_bannerinfomodel_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox_uz',
            field=models.TextField(null=True),
        ),
    ]
