# Generated by Django 4.0 on 2022-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_alter_bannerinfomodel_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='delivery_en',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='delivery_ru',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='delivery_uz',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='inbox_en',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='inbox_ru',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='inbox_uz',
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
