# Generated by Django 4.0 on 2022-09-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0119_remove_bannerinfomodel_delivery_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='category_uz',
        ),
    ]
