# Generated by Django 4.0 on 2022-09-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0120_remove_bannerinfomodel_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='subcategory_en',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='subcategory_ru',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='subcategory_uz',
        ),
    ]
