# Generated by Django 4.0 on 2022-09-25 11:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_alter_bannerinfomodel_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEXWModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('CIP', 'CIP'), ('DAF', 'DAF'), ('EXW', 'EXW'), ('FCA', 'FCA')], default=None, max_length=30, verbose_name='delivery')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('short_descriptions', ckeditor_uploader.fields.RichTextUploadingField()),
                ('long_descriptions', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Delivery',
            },
        ),
    ]
