# Generated by Django 4.0 on 2022-09-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_productexwmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='deliveries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productexwmodel', verbose_name='deliveries'),
        ),
    ]
