# Generated by Django 4.0 on 2022-09-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_bannerinfomodel_deliveries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerinfomodel',
            old_name='deliveries',
            new_name='sent',
        ),
    ]
