# Generated by Django 4.0 on 2022-09-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_rename_deliveries_bannerinfomodel_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='sent',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productexwmodel', verbose_name='type'),
        ),
    ]
