# Generated by Django 4.0 on 2022-09-29 14:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0127_remove_bannerinfomodel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='priceType',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='priceType'),
        ),
    ]
