# Generated by Django 4.0 on 2022-09-29 15:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0128_alter_bannerinfomodel_pricetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='priceType',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_image',
            field=models.FileField(null=True, upload_to='price_image', verbose_name='price_image'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_title',
            field=models.CharField(max_length=300, null=True, verbose_name='price_title'),
        ),
    ]
