# Generated by Django 4.0 on 2022-09-29 15:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_remove_bannerinfomodel_pricetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_short_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='price_title'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='price_title'),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='price_title'),
        ),
    ]
