# Generated by Django 4.0 on 2022-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0130_bannerinfomodel_price_long_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_image',
            field=models.ImageField(null=True, upload_to='price_image', verbose_name='price_image'),
        ),
    ]
