# Generated by Django 4.0 on 2022-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0131_alter_bannerinfomodel_price_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='price_image',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image', verbose_name='image'),
        ),
    ]
