# Generated by Django 4.0 on 2022-09-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0132_remove_bannerinfomodel_price_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='image',
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='price_image',
            field=models.ImageField(null=True, upload_to='price_image', verbose_name='price_image'),
        ),
    ]
