# Generated by Django 4.0 on 2022-10-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0133_remove_bannerinfomodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
