# Generated by Django 4.0 on 2022-10-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0134_bannerinfomodel_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_category', to='home.categorymodel', verbose_name='category'),
        ),
    ]
