# Generated by Django 4.0 on 2022-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0135_alter_bannerinfomodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_image',
            field=models.ImageField(blank=True, null=True, upload_to='price_image', verbose_name='price_image'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='price_title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='price_title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='price_title'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_title_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='price_title'),
        ),
    ]
