# Generated by Django 4.0 on 2022-10-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0136_alter_bannerinfomodel_price_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, verbose_name='delivery'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='inbox',
            field=models.CharField(blank=True, max_length=50, verbose_name='inbox'),
        ),
    ]
