# Generated by Django 4.0 on 2022-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0141_remove_bannerinfomodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='slug',
            field=models.SlugField(max_length=400, null=True, unique=True),
        ),
    ]
