# Generated by Django 4.0 on 2022-11-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0142_bannerinfomodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfomodel',
            name='slug_en',
            field=models.SlugField(max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='slug_ru',
            field=models.SlugField(max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bannerinfomodel',
            name='slug_uz',
            field=models.SlugField(max_length=400, null=True, unique=True),
        ),
    ]
