# Generated by Django 4.0 on 2022-11-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0143_bannerinfomodel_slug_en_bannerinfomodel_slug_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='slug_uz',
        ),
    ]
