# Generated by Django 4.0 on 2022-11-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0144_remove_bannerinfomodel_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerinfomodel',
            name='slug',
        ),
    ]
