# Generated by Django 4.1.1 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0145_remove_bannerinfomodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_long_description',
            field=models.TextField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_long_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_long_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_long_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='price_long'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_short_description',
            field=models.TextField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='price_short_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='price_short'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='short_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
    ]
