# Generated by Django 4.1.1 on 2023-04-15 09:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0146_alter_bannerinfomodel_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='bannerinfomodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='long_description'),
        ),
    ]
