# Generated by Django 4.0 on 2021-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='video',
            field=models.FileField(null=True, upload_to='about_video', verbose_name='video'),
        ),
    ]
