# Generated by Django 4.0 on 2021-12-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutmodel_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='video',
            new_name='image2',
        ),
    ]
