# Generated by Django 4.0 on 2021-12-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_video_aboutmodel_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='image2',
            new_name='video',
        ),
    ]
