# Generated by Django 4.0.2 on 2022-02-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_image2_aboutmodel_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
    ]
