# Generated by Django 4.0 on 2022-02-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_aboutmodel_video_videomodel_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
