# Generated by Django 4.0 on 2022-02-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_contactmodel_delete_requestsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='RequestsModel',
        ),
        migrations.AlterModelOptions(
            name='requestsmodel',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
