# Generated by Django 4.0 on 2022-02-25 11:32

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_aboutmodel_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
