# Generated by Django 4.0 on 2022-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_aboutmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='long_description_en',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='long_description_ru',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='long_description_uz',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_en',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_ru',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_uz',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
    ]
