# Generated by Django 4.0 on 2022-03-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_aboutmodel_description_en_aboutmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestsmodel',
            options={'verbose_name': 'call center', 'verbose_name_plural': 'call center'},
        ),
    ]
