# Generated by Django 4.0 on 2022-03-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_alter_aboutmodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='long_description_en',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='long_description_ru',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='long_description_uz',
        ),
    ]
