# Generated by Django 4.0 on 2022-04-15 13:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_remove_aboutmodel_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=90, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=90, null=True, verbose_name='title'),
        ),
    ]
