# Generated by Django 4.0 on 2022-11-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_alter_aboutmodel_title_alter_aboutmodel_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'ordering': ['-pk'], 'verbose_name': 'about', 'verbose_name_plural': 'abouts'},
        ),
    ]
