# Generated by Django 4.1.5 on 2023-02-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_alter_aboutmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='image',
            field=models.FileField(upload_to='about', verbose_name='image'),
        ),
    ]
