# Generated by Django 4.1.1 on 2023-03-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_alter_aboutmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_uz', models.FileField(upload_to='banner_image_uz', verbose_name='img_uz')),
                ('img_ru', models.FileField(upload_to='banner_image_uz', verbose_name='img_ru')),
                ('img_en', models.FileField(upload_to='banner_image_uz', verbose_name='img_en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
            },
        ),
    ]
