# Generated by Django 4.1.1 on 2023-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_alter_transmodel_img_en_alter_transmodel_img_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmodel',
            name='link',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='transmodel',
            name='img_en',
            field=models.FileField(blank=True, null=True, upload_to='banner_image_en', verbose_name='img_en'),
        ),
        migrations.AlterField(
            model_name='transmodel',
            name='img_ru',
            field=models.FileField(blank=True, null=True, upload_to='banner_image_ru', verbose_name='img_ru'),
        ),
    ]
