# Generated by Django 4.1.1 on 2023-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_transmodel_link_alter_transmodel_img_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
