# Generated by Django 4.0 on 2022-03-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0064_alter_secondsubcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='phone')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('products', models.ManyToManyField(related_name='orders', to='home.BannerInfoModel', verbose_name='products')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
