# Generated by Django 4.0 on 2022-03-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordermodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='products',
        ),
    ]
