# Generated by Django 4.0 on 2022-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_secondsubcategorymodel_category_and_more'),
        ('orders', '0005_remove_ordermodel_price_remove_ordermodel_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='home.BannerInfoModel', verbose_name='products'),
        ),
    ]
