# Generated by Django 4.0 on 2022-03-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
    ]
