# Generated by Django 4.0 on 2022-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_secondsubcategorymodel_category_and_more'),
        ('orders', '0009_remove_ordermodel_products_ordermodel_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='products',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='home.BannerInfoModel', verbose_name='products'),
        ),
    ]
