# Generated by Django 4.0.2 on 2022-02-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='short_descriptions',
            field=models.TextField(null=True, verbose_name='short_descriptions'),
        ),
    ]
