# Generated by Django 4.0.2 on 2022-02-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_workspecificationsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspecificationsmodel',
            name='work_image',
            field=models.FileField(blank=True, null=True, upload_to='pdf_image', verbose_name='work_image'),
        ),
    ]
