# Generated by Django 4.0 on 2022-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_alter_workspecificationsmodel_options_workimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='descriptions_en',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='short_descriptions_en',
            field=models.TextField(max_length=520, null=True, verbose_name='short_descriptions'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='short_descriptions_ru',
            field=models.TextField(max_length=520, null=True, verbose_name='short_descriptions'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='short_descriptions_uz',
            field=models.TextField(max_length=520, null=True, verbose_name='short_descriptions'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='title_en',
            field=models.CharField(max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='title_ru',
            field=models.CharField(max_length=99, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='title_uz',
            field=models.CharField(max_length=99, null=True, verbose_name='title'),
        ),
    ]
