# Generated by Django 4.0 on 2022-04-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_alter_workmodel_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimagemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='work_single', verbose_name='work_image'),
        ),
    ]
