# Generated by Django 4.1.1 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_alter_workmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='descriptions_en',
            field=models.TextField(blank=True, null=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='descriptions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='descriptions_uz',
            field=models.TextField(blank=True, null=True, verbose_name='descriptions'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='short_descriptions',
            field=models.TextField(blank=True, max_length=520, null=True, verbose_name='short_descriptions'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='short_descriptions_en',
            field=models.TextField(blank=True, max_length=520, null=True, verbose_name='short_descriptions'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='short_descriptions_ru',
            field=models.TextField(blank=True, max_length=520, null=True, verbose_name='short_descriptions'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='short_descriptions_uz',
            field=models.TextField(blank=True, max_length=520, null=True, verbose_name='short_descriptions'),
        ),
    ]
