# Generated by Django 4.1.1 on 2023-04-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_alter_workmodel_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
